#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v
export EDITOR='vim'
if [ -f ~/.shell_local ]; then
    . ~/.shell_local
fi

alias glog='git log --oneline --decorate --color --graph'
alias gst='git status'
